#!/usr/local/bin/zsh

cd ~
home_dir=`pwd`
cd -
echo "Using $home_dir as home directory"

dotfiles_dir="$home_dir/dotfiles"

cd $dotfiles_dir

if [ ! -f $home_dir/.vimrc ]; then
	echo "Linking vim"
	stow vim
fi

if [ ! -f $home_dir/.tmux.conf ]; then
	echo "Linking tmux"
	stow tmux
fi

if [ ! -f $home_dir/.gitconfig ]; then
	echo "Copying gitconfig"
 	cp $dotfiles_dir/git/.gitconfig ~/
fi

cd ~

echo "Set up prezto for zsh"
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

