#!/bin/bash

cd ~
home_dir=`pwd`
cd -
echo "Using $home_dir as home directory"

dotfiles_dir="$home_dir/dotfiles"

if [ ! -f $home_dir/.vimrc ]; then
	echo "Linking .vimrc"
	ln -s $dotfiles_dir/vim/vimrc $home_dir/.vimrc
fi

echo "Linking vim folders"
mkdir $home_dir/.vim/
ln -s $dotfiles_dir/vim/colors $home_dir/.vim/colors

echo "Installing vundle"
if [ ! -d "$home_dir/.vim/bundle/vundle" ]; then
	git clone https://github.com/gmarik/vundle.git $home_dir/.vim/bundle/vundle
fi

vim +BundleInstall +qall

echo "Linking .tmux.conf"
ln -s $dotfiles_dir/tmux/tmux.conf $home_dir/.tmux.conf
