[tools]
# Language runtimes
node = 'lts'
python = '3'
ruby = 'latest'
go = 'latest'
rust = 'latest'

# CLI tools
bun = 'latest'
delta = 'latest'
eza = 'latest'
fzf = 'latest'
gh = 'latest'
jq = 'latest'
k9s = 'latest'
kubectl = 'latest'
kubectx = 'latest'
lazygit = 'latest'
luajit = 'latest'
neovim = 'latest'
ollama = 'latest'
pipx = 'latest'
ripgrep = 'latest'
shellcheck = 'latest'
starship = 'latest'
tmux = 'latest'
vivid = 'latest'
yt-dlp = 'latest'
zoxide = 'latest'

# Backend-specific tools
"npm:pnpm" = 'latest'
"npm:yarn" = 'latest'
'gem:tmuxinator' = 'latest'
'go:golang.org/x/tools/gopls' = 'latest'

[settings]
idiomatic_version_file = true
not_found_auto_install = true

[env]
EDITOR = 'nvim'
