" Some sensible defaults
syntax on
set nocompatible	" get with the times
set nu				" line numbers
set hls				" highlighting
set tabstop=4		" 4 spaces
set shiftwidth=4	" 4 spaces

" Colour me
colorscheme tomorrownight

" Setup for Vundle package manager
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Vundle bundles
	" Vundle itself!
	Bundle 'gmarik/vundle'
	" neocomplcache
	Bundle 'Shougo/neocomplcache'
	" Ctrl+P fuzzy search
	Bundle 'kien/ctrlp.vim'

" Bundle configurations
	" neocomplcache
	let g:neocomplcache_enable_at_startup = 1
	" Ctrl+P
	set wildignore+=*/tmp/*,*.so,*.swp,*.zip,f/*
	let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'

" More setup for Vundle
filetype plugin indent on
