" Some sensible defaults
syntax on
set nocompatible	" get with the times
set nu				" line numbers
set hls				" highlighting
set tabstop=4		" 4 spaces
set shiftwidth=4	" 4 spaces
inoremap jj <esc>   " remap `jj` to Esc key
inoremap jk <esc>   " remap `jk` to Esc key


" Setup for Vundle package manager
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Vundle bundles
	" Vundle itself!
	Bundle 'gmarik/vundle'
	" Colorscheme pack
	Plugin 'flazz/vim-colorschemes'
	" neocomplcache
	Bundle 'Shougo/neocomplcache'
	" Ctrl+P fuzzy search
	Bundle 'kien/ctrlp.vim'
	" scss syntax
	Bundle 'cakebaker/scss-syntax.vim'
	" jsx syntax
	Plugin 'pangloss/vim-javascript'
	Plugin 'mxw/vim-jsx'

" Bundle configurations
	" neocomplcache
	let g:neocomplcache_enable_at_startup = 1
	" Ctrl+P
	set wildignore+=*/tmp/*,*.so,*.swp,*.zip,f/*,compiledTemplates/*
	let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'

" Colour me (this needs to happen after colorschemes are installed via vundle
colorscheme Tomorrow-Night-Eighties

" More setup for Vundle
filetype plugin indent on
